# Generated by Django 5.2.1 on 2025-05-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_unpublish_product", "Может отменять публикацию товара")],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте, если товар уже готов к показу на сайте",
                verbose_name="Опубликовано",
            ),
        ),
    ]
